### ISSUE TITLE
[HELP] Invalid Host Header

### ISSUE THREAD

**Issue by mzch** [satellity/satellity#45]
I run satellity but it only responds `Invalid Host Header`.
Could you tell me how to fix this issue?

p.s.
I did `yarn build` in app and pointed apache at build directory.
Then click 'Login' and I can see only busy circle as below:
<img width="1273" alt="ScreenShot 2019-11-18 10 58 17" src="https://user-images.githubusercontent.com/621178/69019097-76e9f080-09f2-11ea-8fbb-6377b4f72995.png">

**Comment by jadeydi** [comment]
I think you don't have access for your http server.

**Comment by mzch** [comment]
Hi @jadeydi ,
? I have access to my web server. please test https://prebbs.com

**Comment by mzch** [comment]
My config.yaml
```
default: &default
  name: Open BBS for people who are instrested in the Internet Technology.
  http:
    host: https://prebbs.com
    port: 4000
  database:
    user: satellity
    password: "xxxxxx"
    host: 192.168.207.11
    port: 5432
  github:
    client_id: xxxxxx
    client_secret: xxxxxx
  system:
    attachments:
      storage: "local"
      path: "/srv/satellity/assets"
  recaptcha: # will be ignore if url or secret is blank
    url: https://www.google.com/recaptcha/api/siteverify
    secret: "xxxxxx"
    site_key: "xxxxxx"
  operators:
    - mzch@mzch.org
  email:
    verification:
      title: "Register An Satellity Account"
      reset: "Reset Your Satellity Account"
      body: "Your verification code: <b>%s</b>"
  mailgun:
    domain: "mailgun.prebbs.com"
    key: "xxxxxxxx"
    sender: "no-replay@prebbs.com"


development:
  <<: *default
  database:
    name: satellity_dev

test:
  <<: *default
  database:
    name: satellity_test

production:
  <<: *default
  database:
    name: satellity
```
And started by `satellity -e production`
